# Topics Advertised
TrajectoryTopic:            '/example0/trajectory'
WayPointsTopic:             '/example0/waypoints'
RouteTopic:                 '/example0/route'
AccTopic:                   '/example0/acc'

# Frame Name
FrameName:                  'world'

# Params
WeightT:                     100.0

WeightAcc:                   0.0

WeightJerk:                  0.5

MaxAccRate:                  4.00

MaxVelRate:                  8.00

Iterations:                  23

Epsilon:                     0.02
